travis:
  secure:
    BINSTAR_TOKEN: PHRk1IgBMGoBvr+Qb1ahgVByTJ3JEu9HNbyZfTyXmFmemi8J3VwfcVvxYO80BvNXhdA74PDBdBElAZ3WnOPykhbJH9kkgwG2jgS6yydFmbkOJZACTIf9veNpycEZyZ1cRTknbn6GxKDkBsenvQ4tSLZJNF8z4yoRReZjVZ9mSELXH6uFNFMzEObG0R95t7K/1LNRgeOdIpc6iT8ahR7B9IJfkp0Kj4ktpCpSBwMWwtxor4YdCf3gscpaxPGXdYx3VXbZ2Vt3f96HUMVA3urKrD++ND97I8PVE0POHtJFJ1Ze/wtnUf2JpcnJ1fzBdYy0n19gCdHqmRbMPHbUaFAoH4Eh7idIM9+bTMumvZ9zfJQV2YXRM1pqM2186jwEnwY317Y/u5e4hr/DLlUqi+x/cATQEjoe8MsOddxmxzWSh1BBvRPZyC5iQXvMqHYbbnSJCoP1fE7oBKLujGkD1x20mzPhQ3jlyd03+OQNJQSzAAALVHjO3xDzK1hZuBwaSVwqS8sABmPxqt5ht4Hu2T5eyLbXxhmrFI9/MaFbie+LWk25SAmql7MhPln8fXN7ptU1J5KLsONRyo+wdm3twA7GnSOjz9GhHsspiWAAgONOgRKRvNx1W46PB5DSowKraU3NMqqKsp+sVwQG/a5y6bFgJFLXIbWFL2M3g/mhtus+P9A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
